include mk/master.mk

export VHOST_USER
export WITH_LINUX

# specify upstream package as SUBDIRS - common terms as suggest by gnu-make
SUBDIRS =
SUBDIRS += ovs
WITH_LINUX=/lib/modules/`uname -r`/build
VHOST_USER = n
include mk/make-subsys.mk
